config/routes.rb
Rails.application.routes.draw do
  resources :promo_banners
  resources :shippings
  resources :payments
  resources :discounts
  resources :order_items
  resources :orders
  resources :stocks
  resources :categories
  resources :products
  get "dashboard/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :products
end

app/models/discount.rb
# == Schema Information
#
# Table name: discounts
#
#  id               :integer          not null, primary key
#  code             :string
#  discount_percent :decimal(, )
#  valid_until      :date
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Discount < ApplicationRecord
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  total_price :decimal(, )
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_one :payment
  has_one :shipping
end

app/models/order_item.rb
# == Schema Information
#
# Table name: order_items
#
#  id         :integer          not null, primary key
#  order_id   :integer          not null
#  product_id :integer          not null
#  quantity   :integer
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer          not null, primary key
#  order_id   :integer          not null
#  method     :string
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  category_id :integer          not null
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :category
  has_one :stock
end

app/models/promo_banner.rb
# == Schema Information
#
# Table name: promo_banners
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class PromoBanner < ApplicationRecord
end

app/models/shipping.rb
# == Schema Information
#
# Table name: shippings
#
#  id              :integer          not null, primary key
#  order_id        :integer          not null
#  pickup_location :string
#  status          :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Shipping < ApplicationRecord
  belongs_to :order
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  product_id :integer          not null
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  email              :string           not null
#  encrypted_password :string(128)      not null
#  confirmation_token :string(128)
#  remember_token     :string(128)      not null
#  admin              :boolean          default("0")
#

class User < ApplicationRecord
  include Clearance::User

  has_many :orders
end

app/controllers/promo_banners_controller.rb
class PromoBannersController < ApplicationController
  before_action :set_promo_banner, only: %i[ show edit update destroy ]

  # GET /promo_banners or /promo_banners.json
  def index
    @promo_banners = PromoBanner.all
  end

  # GET /promo_banners/1 or /promo_banners/1.json
  def show
  end

  # GET /promo_banners/new
  def new
    @promo_banner = PromoBanner.new
  end

  # GET /promo_banners/1/edit
  def edit
  end

  # POST /promo_banners or /promo_banners.json
  def create
    @promo_banner = PromoBanner.new(promo_banner_params)

    respond_to do |format|
      if @promo_banner.save
        format.html { redirect_to @promo_banner, notice: "Promo banner was successfully created." }
        format.json { render :show, status: :created, location: @promo_banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @promo_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promo_banners/1 or /promo_banners/1.json
  def update
    respond_to do |format|
      if @promo_banner.update(promo_banner_params)
        format.html { redirect_to @promo_banner, notice: "Promo banner was successfully updated." }
        format.json { render :show, status: :ok, location: @promo_banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @promo_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_banners/1 or /promo_banners/1.json
  def destroy
    @promo_banner.destroy!

    respond_to do |format|
      format.html { redirect_to promo_banners_path, status: :see_other, notice: "Promo banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_banner
      @promo_banner = PromoBanner.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def promo_banner_params
      params.expect(promo_banner: [ :title, :description, :image_url, :active ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_mena(cena)
    number_to_currency(cena)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def footer
    content_for(:footer) { render 'layouts/footer' }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/promo_banners_helper.rb
module PromoBannersHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/promo_banners/_form.html.erb
<%= form_with(model: promo_banner) do |form| %>
  <% if promo_banner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(promo_banner.errors.count, "error") %> prohibited this promo_banner from being saved:</h2>

      <ul>
        <% promo_banner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.checkbox :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/promo_banners/_promo_banner.html.erb
<div id="<%= dom_id promo_banner %>">
  <p>
    <strong>Title:</strong>
    <%= promo_banner.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= promo_banner.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= promo_banner.image_url %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= promo_banner.active %>
  </p>

</div>

app/views/promo_banners/edit.html.erb
<% content_for :title, "Editing promo banner" %>

<h1>Editing promo banner</h1>

<%= render "form", promo_banner: @promo_banner %>

<br>

<div>
  <%= link_to "Show this promo banner", @promo_banner %> |
  <%= link_to "Back to promo banners", promo_banners_path %>
</div>

app/views/promo_banners/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Promo banners" %>

<h1>Promo banners</h1>

<div id="promo_banners">
  <% @promo_banners.each do |promo_banner| %>
    <%= render promo_banner %>
    <p>
      <%= link_to "Show this promo banner", promo_banner %>
    </p>
  <% end %>
</div>

<%= link_to "New promo banner", new_promo_banner_path %>

app/views/promo_banners/new.html.erb
<% content_for :title, "New promo banner" %>

<h1>New promo banner</h1>

<%= render "form", promo_banner: @promo_banner %>

<br>

<div>
  <%= link_to "Back to promo banners", promo_banners_path %>
</div>

app/views/promo_banners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @promo_banner %>

<div>
  <%= link_to "Edit this promo banner", edit_promo_banner_path(@promo_banner) %> |
  <%= link_to "Back to promo banners", promo_banners_path %>

  <%= button_to "Destroy this promo banner", @promo_banner, method: :delete %>
</div>