config/routes.rb
Rails.application.routes.draw do
  resources :promo_banners
  resources :shippings
  resources :payments
  resources :discounts
  resources :order_items
  resources :orders
  resources :stocks
  resources :categories
  resources :products
  get "dashboard/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :products
end

app/models/discount.rb
# == Schema Information
#
# Table name: discounts
#
#  id               :integer          not null, primary key
#  code             :string
#  discount_percent :decimal(, )
#  valid_until      :date
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Discount < ApplicationRecord
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  total_price :decimal(, )
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_one :payment
  has_one :shipping
end

app/models/order_item.rb
# == Schema Information
#
# Table name: order_items
#
#  id         :integer          not null, primary key
#  order_id   :integer          not null
#  product_id :integer          not null
#  quantity   :integer
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer          not null, primary key
#  order_id   :integer          not null
#  method     :string
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  category_id :integer          not null
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :category
  has_one :stock
end

app/models/promo_banner.rb
# == Schema Information
#
# Table name: promo_banners
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class PromoBanner < ApplicationRecord
end

app/models/shipping.rb
# == Schema Information
#
# Table name: shippings
#
#  id              :integer          not null, primary key
#  order_id        :integer          not null
#  pickup_location :string
#  status          :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Shipping < ApplicationRecord
  belongs_to :order
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  product_id :integer          not null
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  email              :string           not null
#  encrypted_password :string(128)      not null
#  confirmation_token :string(128)
#  remember_token     :string(128)      not null
#  admin              :boolean          default("0")
#

class User < ApplicationRecord
  include Clearance::User

  has_many :orders
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_mena(cena)
    number_to_currency(cena)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def footer
    content_for(:footer) { render 'layouts/footer' }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_footer.html.erb
<!--<footer>-->
<!--  <p>&copy; <%#= Time.now.year %> MIKOshop. All rights reserved. Powered by TEKKA. </p>-->
<!--  <nav>-->
<!--    <ul>-->
<!--      <li><a href="#">Privacy Policy</a></li>-->
<!--      <li><a href="#">Terms of Service</a></li>-->
<!--      <li><a href="#">Contact Us</a></li>-->
<!--    </ul>-->
<!--  </nav>-->
<!--</footer>-->

<!-- Footer -->
<!--<div id="footer">-->
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <section class="col-3 col-6-narrower col-12-mobilep">-->
<!--        <h3>Links to Stuff</h3>-->
<!--        <ul class="links">-->
<!--          <li><a href="#">Mattis et quis rutrum</a></li>-->
<!--          <li><a href="#">Suspendisse amet varius</a></li>-->
<!--          <li><a href="#">Sed et dapibus quis</a></li>-->
<!--          <li><a href="#">Rutrum accumsan dolor</a></li>-->
<!--          <li><a href="#">Mattis rutrum accumsan</a></li>-->
<!--          <li><a href="#">Suspendisse varius nibh</a></li>-->
<!--          <li><a href="#">Sed et dapibus mattis</a></li>-->
<!--        </ul>-->
<!--      </section>-->
<!--      <section class="col-3 col-6-narrower col-12-mobilep">-->
<!--        <h3>More Links to Stuff</h3>-->
<!--        <ul class="links">-->
<!--          <li><a href="#">Duis neque nisi dapibus</a></li>-->
<!--          <li><a href="#">Sed et dapibus quis</a></li>-->
<!--          <li><a href="#">Rutrum accumsan sed</a></li>-->
<!--          <li><a href="#">Mattis et sed accumsan</a></li>-->
<!--          <li><a href="#">Duis neque nisi sed</a></li>-->
<!--          <li><a href="#">Sed et dapibus quis</a></li>-->
<!--          <li><a href="#">Rutrum amet varius</a></li>-->
<!--        </ul>-->
<!--      </section>-->
<!--      <section class="col-6 col-12-narrower">-->
<!--        <h3>Get In Touch</h3>-->
<!--        <form>-->
<!--          <div class="row gtr-50">-->
<!--            <div class="col-6 col-12-mobilep">-->
<!--              <input type="text" name="name" id="name" placeholder="Name" />-->
<!--            </div>-->
<!--            <div class="col-6 col-12-mobilep">-->
<!--              <input type="email" name="email" id="email" placeholder="Email" />-->
<!--            </div>-->
<!--            <div class="col-12">-->
<!--              <textarea name="message" id="message" placeholder="Message" rows="5"></textarea>-->
<!--            </div>-->
<!--            <div class="col-12">-->
<!--              <ul class="actions">-->
<!--                <li><input type="submit" class="button alt" value="Send Message" /></li>-->
<!--              </ul>-->
<!--            </div>-->
<!--          </div>-->
<!--        </form>-->
<!--      </section>-->
<!--    </div>-->
<!--  </div>-->

  <!-- Icons -->
<!--  <ul class="icons">-->
<!--    <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>-->
<!--    <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>-->
<!--    <li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>-->
<!--    <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">LinkedIn</span></a></li>-->
<!--    <li><a href="#" class="icon brands fa-google-plus-g"><span class="label">Google+</span></a></li>-->
<!--  </ul>-->

  <!-- Copyright -->
  <div class="copyright">
    <ul class="menu">
      <li>&copy; <%#= Time.now.year %> MIKOshop. All rights reserved.</li><li>Powered by: <a href="#">TEKKA</a></li>
    </ul>
  </div>

</div>

app/views/layouts/_header.html.erb
<!-- Header -->
<div id="header">
  <!-- Nav -->
  <nav id="nav">
    <ul>
      <li><%= image_tag asset_path('logo_spssol.png'), size: "200x50" %></li>
      <li><a>SPŠS OLOMOUC Merch</a></li>
      <li class="current"><%= link_to "Domů", root_path %></li>
      <li><a href="#">Mikiny</a></li>
      <li><a href="#">Trička</a></li>
      <li><a href="#">Obuv</a></li>
      <li><a href="#">Doplňky</a></li>


      <% if signed_in? %>
        <% if current_user.admin? %>
          <li>
            <a href="#">Administrace</a>
            <ul>
              <li><%= link_to "Kategorie", categories_path %></li>
              <li><%= link_to "Produkty", products_path %></li>
              <li><%= link_to "PŘIDAT PRODUKT", new_product_path %></li>
              <li><%= link_to "Zásoby", stocks_path %></li>
              <li><hr></li>
              <li><%= link_to "Slevy", discounts_path %></li>
              <li><%= link_to "Promo banery", promo_banners_path %></li>
              <li><hr></li>
              <li><%= link_to "Objednávky", orders_path %></li>
              <li><%= link_to "Shipping", shippings_path %></li>
              <li><%= link_to "Platby", payments_path %></li>
              <li><hr></li>
              <li><%= link_to "Uživatelé", users_path %></li>

<!--              <li>-->
<!--                <a href="#">Submenu</a>-->
<!--                <ul>-->
<!--                  <li><a href="#">Lorem dolor</a></li>-->
<!--                  <li><a href="#">Phasellus magna</a></li>-->
<!--                  <li><a href="#">Magna phasellus</a></li>-->
<!--                  <li><a href="#">Etiam nisl</a></li>-->
<!--                  <li><a href="#">Veroeros feugiat</a></li>-->
<!--                </ul>-->
<!--              </li>-->
              <li><a href="#">Veroeros feugiat</a></li>
            </ul>
          </li>
        <% end %>
        <li><a><%= current_user.email %></a></li>
        <li><%= button_to "Sign out", sign_out_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", sign_in_path %></li>
      <% end %>
    </ul>
  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "MIKOshop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body class="is-preload">
    <div id="page-wrapper">
      <%= render 'layouts/header' %>

      <div id="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= content_tag :h1, yield(:title) if show_title? %>
      </div>

      <!-- Main -->
      <section class="wrapper style1">
        <div class="container">
          <div id="content">

            <!-- Content -->

            <!-- Highlights -->
            <section class="wrapper style1">
              <div class="container">
                <div class="row gtr-200">

                  <%= yield %>

                </div>
              </div>
            </section>

          </div>
        </div>
      </section>


      <%= render 'layouts/footer' %>
    </div>

    <!-- Scripts -->
    <script src="<%= asset_path('jquery.min.js') %>"></script>
    <script src="<%= asset_path('jquery.dropotron.min.js') %>"></script>
    <script src="<%= asset_path('browser.min.js') %>"></script>
    <script src="<%= asset_path('breakpoint.min.js') %>"></script>
    <script src="<%= asset_path('util.js') %>"></script>
    <script src="<%= asset_path('main.js') %>"></script>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>